[GAMEPLAY]
#游戏模式，可选 survival，endless，wilderness（生存、无尽、荒野），没有默认值（游戏内会显示服务器是默认模式）
game_mode=
#最大玩家人数（上限64）
max_players=8
#是否开启玩家对战（默认值：否）
pvp=false
#没人时服务器自动暂停（默认值：是）
pause_when_empty=true
#允许投票（默认值：是）
vote_enabled=true

[NETWORK]
#局域网游戏（默认值：否）
lan_only_cluster=false
#服务器密码（不主动填写就是没密码）
cluster_password=服务器密码
#服务器描述（默认无）
cluster_description = 服务器描述
#服务器名称（默认值 [Host]'s World）
cluster_name=服务器名称
#离线服务器，只有局域网用户能加入，并且依赖所有Steam的任何功能都失效，比如礼物掉落（默认值：否）
offline_cluster=false
#服务器语言 en为英文，zh为中文（默认值：en）
cluster_language=zh
#预留位置（默认值：0）
whitelist_slots=0
#通信频率，越高体验越好，但是会增大服务负担（默认15，填写的数字只能是15~60）
tick_rate=60
#云存档标识符（没有默认值，游戏自己生成，专用服务器不需要此字段）
cluster_cloud_id = 
#是否启用自动存档功能（默认：是）
autosaver_enabled = true
#连接超时（默认值8000，单位毫秒）
connection_timeout = 8000
#挂机超时，设置玩家多长时间无操作会被踢出（默认值1800，单位秒）
idle_timeout = 1800
#DNS，为服务器指定DNS地址（没有默认值）
override_dns = 8.8.8.8

[MISC]
#是否开启控制台（默认：是）
console_enabled=true
#最大快照数量（决定你最多能回档多少次，默认值：6）
max_snapshots=30


[SHARD]
#多层世界服务器，开启洞穴必须要开启这个（默认：否）
shard_enabled=true
#监听IP（默认：127.0.0.1）
bind_ip=127.0.0.1
#主世界IP（默认：127.0.0.1）
master_ip=127.0.0.1
#互联端口（默认：10888）
master_port=10888
#互联密码（默认：defaultPass）
cluster_key=defaultPass


[STEAM]
# 群组服务器，只允许某Steam组的成员加入（默认：否）
steam_group_only=false
# 群组ID，指定某个Steam 组，填写群组ID（没有默认值）         
steam_group_id=
# 群组管理员，开启后，Steam组的管理员拥有服务器的管理权限（默认：否）           
steam_group_admins=false
